import pandas as pd

companies = [
    "Grande Canada Engineering",
    "sectrocontractgroup.com",
    "Millstone Environmental Contracting",
    "Canadian Ready Mix",
    "Harlen Cementing Group",
    "Moss Excavation",
    "Milano Group",
    "easyrock.ca",
    "Patriot Concrete",
    "F&W Construction",
    "Contech Concrete",
    "Bird",
    "BRC Aircraft",
    "Cypress Custom Curb",
    "azimuth-three",
    "hutchinsoninstruments.ca",
    "Steed and Evans",
    "Canada Cargo",
    "Avion Construction Group",
    "Jigsaw",
    "Northern Legendary Construction",
    "Stouffville Redmix",
    "belmont.ca",
    "Mirad Concrete",
    "TwinCan Enterprises",
    "Bobcat Contractors",
    "Betonmobile.ca",
    "mtej.ca",
    "NATC Communications",
    "B&G Contracting Group",
    "Smartless Pure",
    "Kenroc Construction",
    "Davis Constructors & Engineers",
    "Ruel Concrete",
    "Fulton Construction",
    "Kfils Construction",
    "Envirobé Québec",
    "Inter Cultures Sentinelle",
    "B&G Contracting Group",
    "B&G Contracting Group",
    "B&G Contracting Group",
    "Ruel Concrete",
    "Mix On-Site",
    "Milestone Environmental Contracting",
    "Click Groupe",
    "Motion",
    "Enviro-Ex",
    "Mother Earth Tree Services",
    "Multicrete Systems",
    "Betonmobile.ca",
    "Burnaby Blocktop",
    "FRPD",
    "Kelson Group",
    "Northbuilt",
    "Joe & Sons Concrete",
    "concretesupply.ca",
    "Noomsa.ca",
    "Groupe Gilbert",
    "Bird",
    "SERWALL",
    "Powers Construction",
    "Redeemers.net",
    "Instone",
    "FCNG Construction",
    "irvingforest.com",
    "Bondbuild",
    "Penn Co",
    "Fcnq",
    "Valleycurbing",
    "Euroviaqc",
    "Clarkpacificexcavating",
    "Palmeribros",
    "Bronteeconstruction",
    "Rinox",
    "Remoteak",
    "Bargebuilders",
    "Nuvest",
    "Euroviaqc",
    "Klesearthworks",
    "Clickgroup",
    "Bbcontracting",
    "Bronteconstruction",
    "Fisherwavy",
    "Belluz Concrete and Rentals",
    "Alaska-Directional_1",
    "AvranceCorp Development",
    "Bathurst Mobile Readymix",
    "Bonde-lite",
"Penn-co Communication",
"FCNQ Construction",
"Valley Curbing",
"Eurovia Québec",
"KLS Earthworks",
"Fisher Wavy",
"Canadian Barge Builders",
"Click Group",
"Yard At A Time Concrete",
"Canadian Armed Forces",
"Terracon Construction",
"B&B Contracting Group",
"Poirier Brother Paving",
"NuVerf Management Services",
"azimuth-three",
"Miss Excavation",
"Clark Pacific Excavating",
"Vikeshell Contracting",
"Riko Group",
"Prologis",
"Paradigm Pools",
"Samaritans Purse",
"Industra",
"Sustainable Aggregates",
"Florien Construction",
"Steed and Evans",
"The Sapient Co.",
"Rinox Enr Inc",
"Spencer Electric",
"Dominion Construction",
"Multicrete Systems",
"Wilhauk Contracting",
"Magco Concrete",
"Hope City Concrete",
"Davis Constructors & Engineers",
"Keller North America",
"Sustainable Aggregates",
"Northbuilt",
"B&B Contracting Group",
"Northern Blocktop",
"Betonmobile.ca",
"Nuark Nation",
"Colombo Concrete",
"Rinox Enr Inc",
"United States Air Force",
"topcoats",
"The Miller Group",
"Allsmith Builders",
"REMOTE ALASKA SOLUTIONS",
"concreteconnections.ca",
"The Pantry",
"Leduc",
"coexs.com",
"parkinswimpeact.com",
"Total Fence",
"B&B Contracting Group",
"Paradigm Pools",
"The Miller Group",
"Summerside Police",
"Paul Davis Restoration",
"Industra",
"Terra Contracting",
"King Services Construction Group & Developments",
"Felix Technology",
"Inter Cultures Sentinelle",
"The Fence Store",
"trusspechomes.com"
]

df = pd.DataFrame(companies, columns=["primary_company"])